#!/bin/bash

# Script de configuration et déploiement

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   🚀 Configuration du Projet - Gestion des Utilisateurs       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Couleurs
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 Étape 1: Préparation du Repository GitHub${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Créer un nouveau repository sur GitHub:"
echo "   → https://github.com/new"
echo ""
echo "2. Initialiser Git localement:"
echo "   → bash init-git.sh"
echo ""

echo -e "${BLUE}🌐 Étape 2: Déployer le Backend sur Railway${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Créer un compte Railway: https://railway.app"
echo "2. Ajouter votre repository GitHub"
echo "3. Ajouter le service PostgreSQL"
echo "4. Configurer les variables d'environnement:"
echo ""
echo "   DATABASE_URL=postgresql://user:pass@host:5432/dbname"
echo "   SECRET_KEY=your-super-secret-key-min-32-chars"
echo "   ALGORITHM=HS256"
echo "   ACCESS_TOKEN_EXPIRE_MINUTES=30"
echo "   FRONTEND_URL=https://votre-app.vercel.app"
echo "   DEBUG=False"
echo ""
echo "5. Root Directory: backend/api_gateway"
echo "6. Start Command: uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo ""

echo -e "${BLUE}💎 Étape 3: Déployer le Frontend sur Vercel${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Créer un compte Vercel: https://vercel.com"
echo "2. Importer votre repository GitHub"
echo "3. Root Directory: frontend"
echo "4. Ajouter la variable d'environnement:"
echo ""
echo "   VITE_API_URL=https://votre-backend-railway.up.railway.app"
echo ""
echo "5. Cliquer sur Deploy"
echo ""

echo -e "${BLUE}🧪 Étape 4: Tester localement${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Avant de déployer, testez localement:"
echo ""
echo "   docker-compose up"
echo ""
echo "Accédez à:"
echo "   - Frontend: http://localhost:3000"
echo "   - Backend: http://localhost:8000"
echo "   - API Docs: http://localhost:8000/docs"
echo "   - PostgreSQL: localhost:5432"
echo ""

echo -e "${BLUE}📝 Étape 5: Pousser sur GitHub${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Configurer l'URL du repository:"
echo "   git remote add origin https://github.com/votre-username/repo-name.git"
echo ""
echo "2. Pousser le code:"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""

echo -e "${BLUE}✅ Étape 6: Vérifier les déploiements${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ Railway: Vérifier les logs dans le dashboard Railway"
echo "✓ Vercel: Vérifier les logs dans le dashboard Vercel"
echo "✓ GitHub: Vérifier les Actions dans votre repository"
echo ""

echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}🎉 Tout est configuré! Suivez les étapes ci-dessus.${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""

echo -e "${YELLOW}📚 Ressources utiles:${NC}"
echo "  • Guide complet: GUIDE_DEPLOIEMENT.md"
echo "  • README projet: README_DEPLOYMENT.md"
echo "  • Architecture: DEPLOYMENT.md"
echo ""

echo -e "${YELLOW}💡 Astuces:${NC}"
echo "  • Railway redéploie automatiquement quand vous push sur GitHub"
echo "  • Vercel redéploie automatiquement quand vous push sur GitHub"
echo "  • Les logs vous aideront à déboguer les problèmes"
echo "  • N'oubliez pas les variables d'environnement!"
echo ""
